In [15]:
import FinanceDataReader as fdr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup
import requests
import re
import tqdm as tqdm

BaseUrl = 'http://finance.naver.com/sise/entryJongmok.nhn?&page='

stock_codes = []

for i in range(1, 21):  # range() 함수의 끝 파라미터는 포함되지 않는다.
    url = BaseUrl + str(i)
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'lxml')
    items = soup.find_all('td', {'class': 'ctg'})
    for item in items:
        txt = item.a.get('href')  # 예: https://finance.naver.com/item/main.nhn?code=006390
        k = re.search('[\d]+', txt)  # 정규표현식 사용. [\d] 숫자표현, + : 반복
        if k:
            code = k.group()
            stock_codes.append(code)

asset_df = pd.read_csv('csv_files/kospi200_no_nan.csv')
asset_df['Date'] = pd.to_datetime(asset_df['Date'], format='%Y-%m-%d')
asset_df.set_index('Date', inplace=True)

returns_df = np.log(asset_df / asset_df.shift(1)).dropna()
# returns_df = asset_df.pct_change().dropna()
returns_df

,005930,000660,207940,005380,012450,068270,000270,105560,035420,055550,...,069260,001430,003620,005420,006650,002710,178920,093370,105630,006110
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-03,0.005420,-0.002114,-0.015286,-0.017094,0.004309,-0.013987,-0.011834,0.012807,-0.005495,0.003515,...,-0.007308,-0.006689,-0.012134,-0.020399,-0.017392,0.005700,0.011429,0.009776,-0.005780,-0.010471
2020-01-06,0.000000,-0.002119,-0.023982,0.000000,0.008590,-0.025684,-0.002384,-0.011733,-0.005525,-0.015321,...,-0.022251,-0.023770,-0.024613,0.045372,-0.044851,-0.011050,-0.034686,-0.029747,-0.017544,-0.002342
2020-01-07,0.005391,-0.003186,0.016847,-0.004320,-0.014348,0.028494,0.003574,0.008547,0.035378,0.015321,...,0.002497,-0.006897,0.000000,-0.015557,-0.013857,0.011050,0.023257,0.013781,0.020439,0.001172
2020-01-08,0.017762,0.035531,-0.025379,-0.030772,-0.016002,-0.028494,-0.017997,-0.018251,-0.021622,-0.017700,...,-0.038124,-0.046026,-0.059009,-0.060737,-0.042762,-0.047332,-0.053110,-0.049487,-0.053425,-0.016529
2020-01-09,0.031198,0.016294,0.027764,-0.004474,0.005851,0.022859,-0.013407,0.007555,0.016261,0.004751,...,-0.002594,0.003617,0.023479,0.080720,0.038100,0.034365,0.032790,0.085946,0.030032,0.007117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-23,0.009390,0.006507,0.010593,0.021152,0.066586,0.007246,-0.002969,0.013889,-0.043803,0.021528,...,0.015193,0.022751,0.019318,0.038173,0.008833,0.029593,0.040040,0.021761,0.040880,0.024304
2024-12-24,0.016682,-0.006507,-0.011659,0.006953,-0.006154,0.002572,-0.002978,-0.005764,0.007435,0.002026,...,-0.001617,-0.007362,-0.011546,-0.018904,-0.006301,-0.019048,-0.001138,-0.021761,-0.009018,-0.011364
2024-12-26,-0.014815,0.009451,-0.001067,0.004608,-0.001544,-0.015026,0.022605,-0.011628,-0.012923,-0.010173,...,-0.005408,-0.002466,-0.015605,-0.014094,-0.014004,-0.033781,-0.015495,-0.011061,-0.003490,-0.023122
2024-12-27,0.001864,0.025538,-0.003207,-0.011561,-0.014008,-0.013763,-0.019628,-0.005865,-0.011067,-0.011311,...,-0.048329,-0.019951,-0.007895,-0.023500,0.000000,-0.018249,-0.016915,-0.015283,-0.017637,-0.023670
2024-12-30,-0.009355,-0.003444,0.015932,-0.014052,0.023239,0.038602,-0.001984,-0.025016,0.006051,-0.014584,...,-0.030043,-0.004544,-0.003971,0.010513,-0.003854,0.001840,-0.006492,0.021331,0.008505,0.013383

### 티커 코드 -> 티커 종목명 변환

In [16]:
target_tickers = stock_codes

# 전체 한국 상장 종목 불러오기
krx = fdr.StockListing('KRX')

# 티커-종목명 매핑
ticker_filtered_name_dict = {}

for ticker in target_tickers:
    name = krx.loc[krx['Code'] == ticker, 'Name']
    if not name.empty:
        ticker_filtered_name_dict[ticker] = name.values[0]
    else:
        ticker_filtered_name_dict[ticker] = None  # 못 찾은 경우 None 처리

# 결과 확인
print(ticker_filtered_name_dict)

{'005930': '삼성전자', '000660': 'SK하이닉스', '373220': 'LG에너지솔루션', '207940': '삼성바이오로직스', '005380': '현대차', '012450': '한화에어로스페이스', '068270': '셀트리온', '000270': '기아', '329180': 'HD현대중공업', '105560': 'KB금융', '035420': 'NAVER', '055550': '신한지주', '012330': '현대모비스', '042660': '한화오션', '138040': '메리츠금융지주', '005490': 'POSCO홀딩스', '028260': '삼성물산', '009540': 'HD한국조선해양', '034020': '두산에너빌리티', '086790': '하나금융지주', '259960': '크래프톤', '000810': '삼성화재', '032830': '삼성생명', '035720': '카카오', '010130': '고려아연', '015760': '한국전력', '011200': 'HMM', '051910': 'LG화학', '096770': 'SK이노베이션', '033780': 'KT&G', '316140': '우리금융지주', '030200': 'KT', '010140': '삼성중공업', '064350': '현대로템', '024110': '기업은행', '006400': '삼성SDI', '402340': 'SK스퀘어', '066570': 'LG전자', '017670': 'SK텔레콤', '352820': '하이브', '267260': 'HD현대일렉트릭', '323410': '카카오뱅크', '003550': 'LG', '018260': '삼성에스디에스', '003670': '포스코퓨처엠', '034730': 'SK', '000100': '유한양행', '009150': '삼성전기', '047050': '포스코인터내셔널', '086280': '현대글로비스', '326030': 'SK바이오팜', '047810': '한국항공우주', '003490': '대한항공', '272210': '한화시스템', '042700': '한미반도체', '003230': '삼양식품', '090430': '아모레퍼시픽', '079550': 'LIG넥스원', '006800': '미래에셋증권', '010620': 'HD현대미포', '005830': 'DB손해보험', '021240': '코웨이', '267250': 'HD현대', '010120': 'LS ELECTRIC', '010950': 'S-Oil', '180640': '한진칼', '051900': 'LG생활건강', '032640': 'LG유플러스', '009830': '한화솔루션', '161390': '한국타이어앤테크놀로지', '005940': 'NH투자증권', '000150': '두산', '271560': '오리온', '029780': '삼성카드', '241560': '두산밥캣', '016360': '삼성증권', '000720': '현대건설', '071050': '한국금융지주', '298040': '효성중공업', '377300': '카카오페이', '034220': 'LG디스플레이', '006260': 'LS', '450080': '에코프로머티', '011790': 'SKC', '251270': '넷마블', '028050': '삼성E&A', '022100': '포스코DX', '001040': 'CJ', '000880': '한화', '097950': 'CJ제일제당', '078930': 'GS', '036460': '한국가스공사', '035250': '강원랜드', '128940': '한미약품', '039490': '키움증권', '175330': 'JB금융지주', '011070': 'LG이노텍', '138930': 'BNK금융지주', '004020': '현대제철', '454910': '두산로보틱스', '036570': '엔씨소프트', '011780': '금호석유화학', '302440': 'SK바이오사이언스', '489790': '한화비전', '017800': '현대엘리베이터', '278470': '에이피알', '383220': 'F&F', '052690': '한전기술', '026960': '동서', '011170': '롯데케미칼', '139480': '이마트', '004370': '농심', '018880': '한온시스템', '012750': '에스원', '004990': '롯데지주', '066970': '엘앤에프', '088350': '한화생명', '081660': '미스토홀딩스', '002380': 'KCC', '001440': '대한전선', '030000': '제일기획', '111770': '영원무역', '008930': '한미사이언스', '001450': '현대해상', '051600': '한전KPS', '192820': '코스맥스', '023530': '롯데쇼핑', '000120': 'CJ대한통운', '282330': 'BGF리테일', '002790': '아모레퍼시픽홀딩스', '161890': '한국콜마', '028670': '팬오션', '204320': 'HL만도', '008770': '호텔신라', '139130': 'iM금융지주', '375500': 'DL이앤씨', '103140': '풍산', '112610': '씨에스윈드', '007310': '오뚜기', '361610': 'SK아이이테크놀로지', '069620': '대웅제약', '042670': 'HD현대인프라코어', '006360': 'GS건설', '005850': '에스엘', '004170': '신세계', '047040': '대우건설', '006280': '녹십자', '009420': '한올바이오파마', '000240': '한국앤컴퍼니', '073240': '금호타이어', '000080': '하이트진로', '069960': '현대백화점', '014680': '한솔케미칼', '009970': '영원무역홀딩스', '457190': '이수스페셜티케미컬', '005070': '코스모신소재', '300720': '한일시멘트', '007070': 'GS리테일', '010060': 'OCI홀딩스', '192080': '더블유게임즈', '003090': '대웅', '011210': '현대위아', '001800': '오리온홀딩스', '137310': '에스디바이오센서', '185750': '종근당', '280360': '롯데웰푸드', '001120': 'LX인터내셔널', '298020': '효성티앤씨', '005300': '롯데칠성', '336260': '두산퓨얼셀', '009240': '한샘', '004490': '세방전지', '014820': '동원시스템즈', '003030': '세아제강지주', '001740': 'SK네트웍스', '002840': '미원상사', '004000': '롯데정밀화학', '003240': '태광산업', '039130': '하나투어', '120110': '코오롱인더', '001680': '대상', '145720': '덴티움', '298050': 'HS효성첨단소재', '114090': 'GKL', '008730': '율촌화학', '285130': 'SK케미칼', '000210': 'DL', '005250': '녹십자홀딩스', '069260': 'TKG휴켐스', '001430': '세아베스틸지주', '003620': 'KG모빌리티', '005420': '코스모화학', '006650': '대한유화', '002710': 'TCC스틸', '456040': 'OCI', '271940': '일진하이솔루스', '178920': 'PI첨단소재', '093370': '후성', '105630': '한세실업', '006110': '삼아알미늄'}

In [17]:
columns_renamed = {}

for col in returns_df.columns:
    if col == 'Date':
        columns_renamed[col] = 'Date'
    else:
        columns_renamed[col] = ticker_filtered_name_dict.get(col, col)  # 매칭 안 되면 기존 col 이름 유지

# 컬럼명 변경
returns_df.rename(columns=columns_renamed, inplace=True)

# 결과 확인
returns_df.head()

,삼성전자,SK하이닉스,삼성바이오로직스,현대차,한화에어로스페이스,셀트리온,기아,KB금융,NAVER,신한지주,...,TKG휴켐스,세아베스틸지주,KG모빌리티,코스모화학,대한유화,TCC스틸,PI첨단소재,후성,한세실업,삼아알미늄
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-03,0.005420,-0.002114,-0.015286,-0.017094,0.004309,-0.013987,-0.011834,0.012807,-0.005495,0.003515,...,-0.007308,-0.006689,-0.012134,-0.020399,-0.017392,0.005700,0.011429,0.009776,-0.005780,-0.010471
2020-01-06,0.000000,-0.002119,-0.023982,0.000000,0.008590,-0.025684,-0.002384,-0.011733,-0.005525,-0.015321,...,-0.022251,-0.023770,-0.024613,0.045372,-0.044851,-0.011050,-0.034686,-0.029747,-0.017544,-0.002342
2020-01-07,0.005391,-0.003186,0.016847,-0.004320,-0.014348,0.028494,0.003574,0.008547,0.035378,0.015321,...,0.002497,-0.006897,0.000000,-0.015557,-0.013857,0.011050,0.023257,0.013781,0.020439,0.001172
2020-01-08,0.017762,0.035531,-0.025379,-0.030772,-0.016002,-0.028494,-0.017997,-0.018251,-0.021622,-0.017700,...,-0.038124,-0.046026,-0.059009,-0.060737,-0.042762,-0.047332,-0.053110,-0.049487,-0.053425,-0.016529
2020-01-09,0.031198,0.016294,0.027764,-0.004474,0.005851,0.022859,-0.013407,0.007555,0.016261,0.004751,...,-0.002594,0.003617,0.023479,0.080720,0.038100,0.034365,0.032790,0.085946,0.030032,0.007117

### 클러스터 별 종목 구성 리스트 가져오기

In [18]:
cluster_0 = ['BGF리테일', 'CJ대한통운', 'CJ제일제당', 'DB손해보험', 'DL', 'DL이앤씨', 'GS', 'HD현대인프라코어',
             'HD현대일렉트릭', 'HS효성첨단소재', 'KCC', 'KT&G', 'LG', 'LG생활건강', 'LG이노텍', 'LIG넥스원',
             'LS', 'LS ELECTRIC', 'LX인터내셔널', 'OCI', 'OCI홀딩스', 'PI첨단소재', 'S-Oil', 'SK바이오사이언스',
             'SK아이이테크놀로지', 'SK케미칼', 'SK텔레콤', 'TCC스틸', 'TKG휴켐스', '강원랜드', '고려아연', '금호석유화학',
             '농심', '대상', '대웅', '대웅제약', '더블유게임즈', '덴티움', '동서', '동원시스템즈', '두산밥캣', '롯데정밀화학',
             '롯데칠성', '메리츠금융지주', '미스토홀딩스', '미원상사', '삼성E&A', '삼성SDI', '삼성물산', '삼성바이오로직스',
             '삼성에스디에스', '삼성전기', '삼성증권', '삼성카드', '삼성화재', '삼양식품', '세방전지', '세아제강지주', '셀트리온',
             '신세계', '씨에스윈드', '아모레퍼시픽', '아모레퍼시픽홀딩스', '에스엘', '에스원', '엔씨소프트', '영원무역', '영원무역홀딩스',
             '오뚜기', '오리온', '오리온홀딩스', '유한양행', '이수스페셜티케미컬', '제일기획', '종근당', '코스맥스', '코스모신소재',
             '코웨이', '키움증권', '포스코DX', '포스코인터내셔널', '풍산', '하이브', '하이트진로', '한국금융지주', '한국앤컴퍼니',
             '한국콜마', '한국타이어앤테크놀로지', '한국항공우주', '한미사이언스', '한미약품', '한세실업', '한솔케미칼', '한일시멘트',
             '한전KPS', '한전기술', '한화시스템', '한화에어로스페이스', '현대글로비스', '현대로템', '현대엘리베이터', '현대해상',
             '효성중공업', '효성티앤씨']

cluster_1 = ['KB금융', '기업은행', '신한지주', '우리금융지주', '하나금융지주', '한국전력']

cluster_2 = ['F&F', 'HMM', 'NAVER', 'SK바이오팜', 'SK스퀘어', '에스디바이오센서', '에이피알', '크래프톤', '한미반도체', '한진칼']

cluster_3 = ['태광산업']

cluster_4 = ['HD현대', 'LG전자', 'LG화학', 'POSCO홀딩스', 'SK', 'SK이노베이션', 'SK하이닉스', '기아', '한화', '현대모비스', '현대차']

cluster_5 = ['에코프로머티', '카카오페이']

cluster_6 = ['CJ', 'GKL', 'GS건설', 'GS리테일', 'HD한국조선해양', 'HD현대미포', 'HD현대중공업', 'HL만도', 'KG모빌리티',
             'LG에너지솔루션', 'SKC', 'SK네트웍스', '넷마블', '녹십자', '녹십자홀딩스', '대한유화', '대한전선', '두산', '두산퓨얼셀',
             '롯데쇼핑', '롯데웰푸드', '롯데지주', '롯데케미칼', '삼아알미늄', '세아베스틸지주', '엘앤에프', '율촌화학', '이마트',
             '일진하이솔루스', '카카오', '코스모화학', '코오롱인더', '포스코퓨처엠', '하나투어', '한국가스공사', '한샘',
             '한올바이오파마', '한화비전', '한화솔루션', '한화오션', '현대건설', '현대백화점', '현대위아', '현대제철', '호텔신라', '후성']

cluster_7 = ['BNK금융지주', 'JB금융지주', 'KT', 'LG디스플레이', 'LG유플러스', 'NH투자증권', 'iM금융지주', '금호타이어', '대우건설',
             '대한항공', '두산에너빌리티', '미래에셋증권', '삼성생명', '삼성중공업', '카카오뱅크', '팬오션', '한온시스템', '한화생명']

In [28]:
# returns_df에 실제 존재하는 종목 리스트
available_stocks = set(returns_df.columns)

# 클러스터 변수들 (cluster_0 ~ cluster_7)
cluster_vars = [cluster_0, cluster_1, cluster_2, cluster_3, cluster_4, cluster_5, cluster_6, cluster_7]

# returns_df 기준으로 정제된 클러스터 리스트 재정의
filtered_clusters = []

for i, cluster in enumerate(cluster_vars):
    filtered = [stock for stock in cluster if stock in available_stocks]
    print(f"cluster_{i}: {len(cluster)} → {len(filtered)} (available)")
    filtered_clusters.append(filtered)

# 이후에는 이 filtered_clusters[i]를 사용

cluster_0: 104 → 98 (available)
cluster_1: 6 → 6 (available)
cluster_2: 10 → 4 (available)
cluster_3: 1 → 1 (available)
cluster_4: 11 → 11 (available)
cluster_5: 2 → 0 (available)
cluster_6: 46 → 42 (available)
cluster_7: 18 → 17 (available)

In [19]:
# returns_df.to_csv('csv_files/kospi_log_returns.csv')

### In-Sample & Out-Sample 생성

In [31]:
# 데이터 기간 확인
start_date = returns_df.index.min()
end_date = returns_df.index.max()

# 총 기간이 5년임을 고려하여 4년(in-sample), 1년(out-sample)으로 나누기
cutoff_date = start_date + pd.DateOffset(years=4)
returns_in_sample = returns_df.loc[start_date:cutoff_date - pd.DateOffset(days=1)]
returns_out_sample = returns_df.loc[cutoff_date:end_date]

# 결과 미리 보기
returns_in_sample.shape, returns_out_sample.shape, cutoff_date

((987, 180), (243, 180), Timestamp('2024-01-03 00:00:00'))

### Cluster 5(예시)로 구성한 Portfolio와 Random Selected Portfolio 비교

#### 클러스터 개수와 동일하게 random selection

In [32]:
# import random

# # 재현 가능성 확보
# random.seed(42)

# # 전체 종목 리스트
# all_stocks = list(returns_df.columns)

# # 클러스터 변수 리스트
# cluster_vars = [cluster_0, cluster_1, cluster_2, cluster_3, cluster_4, cluster_5, cluster_6, cluster_7]

# # 클러스터별 랜덤 포트폴리오 저장용 딕셔너리
# random_portfolios_by_cluster = {}

# # 각 클러스터에 대해 랜덤 포트폴리오 생성
# for i, cluster in enumerate(cluster_vars):
#     cluster_name = f'cluster_{i}'
#     cluster_len = len(cluster)
    
#     if cluster_len < 5:
#         print(f"{cluster_name}은 종목 수가 {cluster_len}개로 너무 적어서 건너뜁니다.")
#         continue

#     portfolios = []
#     for _ in range(100):
#         selection = random.sample(all_stocks, cluster_len)
#         portfolios.append(selection)
    
#     random_portfolios_by_cluster[cluster_name] = portfolios
#     print(f"{cluster_name}: 랜덤 포트폴리오 100개 생성 완료 (종목 수: {cluster_len})")

#### Cluster Portfolio와 Random Portfolio 구성

In [33]:
from scipy.optimize import minimize
import numpy as np
import pandas as pd

def markowitz_min_variance(returns: pd.DataFrame, target_return: float = 0.01):
    mean_returns = returns.mean().values
    cov_matrix = returns.cov().values
    num_assets = len(mean_returns)

    # 포트폴리오 분산 (리스크) 계산
    def portfolio_variance(weights):
        return weights.T @ cov_matrix @ weights

    # 제약조건: 총합 = 1, 기대 수익률 ≥ target_return
    constraints = [
        {'type': 'eq', 'fun': lambda w: np.sum(w) - 1},
        {'type': 'ineq', 'fun': lambda w: w @ mean_returns - target_return}
    ]

    # 비중 범위 (0~1)
    bounds = tuple((0, 1) for _ in range(num_assets))
    init_guess = np.repeat(1 / num_assets, num_assets)

    result = minimize(portfolio_variance, init_guess, method='SLSQP', bounds=bounds, constraints=constraints)

    if result.success:
        return result.x
    else:
        raise ValueError("최적화 실패: ", result.message)

In [34]:
import random

# 재현 가능성 확보
random.seed(42)

all_stocks = list(returns_df.columns)

cluster_vars = [filtered_clusters[0], filtered_clusters[1], filtered_clusters[2], filtered_clusters[3],
                filtered_clusters[4], filtered_clusters[5], filtered_clusters[6], filtered_clusters[7]]

cluster_results = {}
random_results_by_cluster = {}

for i, cluster in enumerate(cluster_vars):
    cluster_name = f'filtered_cluster_{i}'
    cluster_size = len(cluster)
    
    if cluster_size < 5:
        print(f"{cluster_name}: 종목 수가 {cluster_size}개로 적어 생략")
        continue

    print(f"{cluster_name}: 최적화 및 랜덤 비교 시작 (종목 수 {cluster_size})")

    # (1) 클러스터 포트폴리오 수익률 계산
    try:
        cluster_ret_in = returns_in_sample[cluster].dropna()
        cluster_ret_out = returns_out_sample[cluster].dropna()
        
        weights = markowitz_min_variance(cluster_ret_in, target_return=cluster_ret_in.mean().mean())
        cluster_in_pf = cluster_ret_in @ weights
        cluster_out_pf = cluster_ret_out @ weights

        cluster_results[cluster_name] = {
            'weights': weights,
            'in_sample': cluster_in_pf,
            'out_sample': cluster_out_pf
        }

    except Exception as e:
        print(f"{cluster_name}: 최적화 실패 - {e}")
        continue

    # (2) 랜덤 포트폴리오 100개 생성 및 비교
    random_portfolios = []
    for _ in range(100):
        random_stocks = random.sample(all_stocks, cluster_size)
        random_portfolios.append(random_stocks)

    random_returns_in = []
    random_returns_out = []

    for stock_list in random_portfolios:
        subset_in = returns_in_sample[stock_list].dropna()
        subset_out = returns_out_sample[stock_list].dropna()
        
        # 너무 많은 결측치나 종목 손실 시 skip
        if subset_in.shape[1] < cluster_size * 0.8 or subset_out.shape[1] < cluster_size * 0.8:
            continue

        try:
            rand_weights = markowitz_min_variance(subset_in, target_return=subset_in.mean().mean())
            rand_in_pf = subset_in @ rand_weights
            rand_out_pf = subset_out @ rand_weights

            random_returns_in.append(rand_in_pf)
            random_returns_out.append(rand_out_pf)
        except:
            continue

    random_results_by_cluster[cluster_name] = {
        'in_sample': random_returns_in,
        'out_sample': random_returns_out
    }

    print(f"{cluster_name}: 랜덤 포트폴리오 {len(random_returns_in)}개 완료")

filtered_cluster_0: 최적화 및 랜덤 비교 시작 (종목 수 98)
filtered_cluster_0: 랜덤 포트폴리오 100개 완료
filtered_cluster_1: 최적화 및 랜덤 비교 시작 (종목 수 6)
filtered_cluster_1: 랜덤 포트폴리오 100개 완료
filtered_cluster_2: 종목 수가 4개로 적어 생략
filtered_cluster_3: 종목 수가 1개로 적어 생략
filtered_cluster_4: 최적화 및 랜덤 비교 시작 (종목 수 11)
filtered_cluster_4: 랜덤 포트폴리오 100개 완료
filtered_cluster_5: 종목 수가 0개로 적어 생략
filtered_cluster_6: 최적화 및 랜덤 비교 시작 (종목 수 42)
filtered_cluster_6: 랜덤 포트폴리오 100개 완료
filtered_cluster_7: 최적화 및 랜덤 비교 시작 (종목 수 17)
filtered_cluster_7: 랜덤 포트폴리오 100개 완료

In [41]:
# CVaR 계산 시 예외 처리 추가 (tail 데이터가 없을 경우 NaN 반환)
def sharpe_ratio(returns, risk_free_rate=0.0):
    excess_returns = returns - risk_free_rate
    return np.mean(excess_returns) / np.std(excess_returns)


def sortino_ratio(returns, risk_free_rate=0.0):
    downside_returns = returns[returns < risk_free_rate]
    return np.mean(returns - risk_free_rate) / np.std(downside_returns)


def cvar(returns, alpha=0.05):
    if len(returns) == 0:
        return np.nan
    var_threshold = np.quantile(returns, alpha)
    tail_losses = returns[returns <= var_threshold]
    return tail_losses.mean() if len(tail_losses) > 0 else np.nan

In [42]:
cluster_metrics_summary = {}
random_metrics_summary = {}

for cluster_name in cluster_results.keys():
    print(f"{cluster_name}: 성과지표 계산 시작")

    # 1. 클러스터 포트폴리오 수익률
    cluster_in = cluster_results[cluster_name]['in_sample']
    cluster_out = cluster_results[cluster_name]['out_sample']

    cluster_metrics_summary[cluster_name] = {
        'in_sample': {
            'Sharpe': sharpe_ratio(cluster_in),
            'Sortino': sortino_ratio(cluster_in),
            'CVaR': cvar(cluster_in),
        },
        'out_sample': {
            'Sharpe': sharpe_ratio(cluster_out),
            'Sortino': sortino_ratio(cluster_out),
            'CVaR': cvar(cluster_out),
        }
    }

    # 2. 랜덤 포트폴리오 리스트
    random_in_list = random_results_by_cluster[cluster_name]['in_sample']
    random_out_list = random_results_by_cluster[cluster_name]['out_sample']

    random_metrics_in = []
    random_metrics_out = []

    for r_in, r_out in zip(random_in_list, random_out_list):
        if r_in.empty or r_out.empty:
            continue
        random_metrics_in.append({
            'Sharpe': sharpe_ratio(r_in),
            'Sortino': sortino_ratio(r_in),
            'CVaR': cvar(r_in),
        })
        random_metrics_out.append({
            'Sharpe': sharpe_ratio(r_out),
            'Sortino': sortino_ratio(r_out),
            'CVaR': cvar(r_out),
        })

    random_metrics_summary[cluster_name] = {
        'in_sample': pd.DataFrame(random_metrics_in),
        'out_sample': pd.DataFrame(random_metrics_out)
    }

    print(f"{cluster_name}: 성과지표 계산 완료")

filtered_cluster_0: 성과지표 계산 시작
filtered_cluster_0: 성과지표 계산 완료
filtered_cluster_1: 성과지표 계산 시작
filtered_cluster_1: 성과지표 계산 완료
filtered_cluster_4: 성과지표 계산 시작
filtered_cluster_4: 성과지표 계산 완료
filtered_cluster_6: 성과지표 계산 시작
filtered_cluster_6: 성과지표 계산 완료
filtered_cluster_7: 성과지표 계산 시작
filtered_cluster_7: 성과지표 계산 완료

In [63]:
import os
import pandas as pd
from scipy.stats import ttest_1samp

# 유의성 수준 별표 함수
def significance_stars(p):
    if p <= 0.01:
        return '***'
    elif p <= 0.05:
        return '**'
    elif p <= 0.1:
        return '*'
    else:
        return ''

# 분석 대상 지표
metrics_to_test = ['Sharpe', 'Sortino', 'CVaR']

# 결과 저장 딕셔너리
t_test_results = {}

# 저장 폴더 생성
os.makedirs('results', exist_ok=True)

# 클러스터별 t-test 수행 + 저장
for cluster_name in cluster_metrics_summary.keys():
    t_test_results[cluster_name] = {'in_sample': {}, 'out_sample': {}}

    for period in ['in_sample', 'out_sample']:
        cluster_metrics = cluster_metrics_summary[cluster_name][period]
        random_df = random_metrics_summary[cluster_name][period]

        for metric in metrics_to_test:
            random_values = random_df[metric].dropna()
            cluster_value = cluster_metrics[metric]

            # 단측 t-test: "랜덤 < 클러스터" → cluster가 우월한지 확인
            t_stat, p_val = ttest_1samp(random_values, popmean=cluster_value, alternative='less')

            t_test_results[cluster_name][period][metric] = {
                'Cluster': cluster_value,
                'RandomMean': random_values.mean(),
                'p-value (one-sided >)': p_val,
                'significance': significance_stars(p_val)
            }

        # → 바로 저장
        result_dict = t_test_results[cluster_name][period]
        df = pd.DataFrame(result_dict).T  # metric별 행
        filename = f"results/{cluster_name}_{period}_ttest_results.csv"
        df.to_csv(filename)
        print(f"✅ 저장 완료: {filename}")

✅ 저장 완료: results/filtered_cluster_0_in_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_0_out_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_1_in_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_1_out_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_4_in_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_4_out_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_6_in_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_6_out_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_7_in_sample_ttest_results.csv
✅ 저장 완료: results/filtered_cluster_7_out_sample_ttest_results.csv

#### 결과 예시 1

In [64]:
pd.DataFrame(t_test_results['filtered_cluster_0']['in_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.028426  0.034171 -0.032995
RandomMean             0.022852  0.027704 -0.033877
p-value (one-sided >)       0.0       0.0  0.000033
significance                ***       ***       ***

#### 결과 예시 2

In [65]:
pd.DataFrame(t_test_results['filtered_cluster_0']['out_sample'])

                         Sharpe   Sortino      CVaR
Cluster                -0.01756 -0.020422 -0.028538
RandomMean            -0.025756 -0.030491 -0.029263
p-value (one-sided >)       0.0       0.0  0.000008
significance                ***       ***       ***

#### 결과 예시 3

In [66]:
pd.DataFrame(t_test_results['filtered_cluster_1']['in_sample'])

                         Sharpe   Sortino      CVaR
Cluster               -0.000391  -0.00056 -0.037654
RandomMean             0.017724  0.024358  -0.03787
p-value (one-sided >)       1.0       1.0  0.262972
significance

#### 결과 예시 4

In [67]:
pd.DataFrame(t_test_results['filtered_cluster_1']['out_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.051728  0.076379 -0.039422
RandomMean            -0.018641 -0.024801  -0.03554
p-value (one-sided >)       0.0       0.0       1.0
significance                ***       ***

#### 결과 예시 5

In [68]:
pd.DataFrame(t_test_results['filtered_cluster_4']['in_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.015671  0.021732 -0.038187
RandomMean             0.020788  0.027177 -0.036392
p-value (one-sided >)  0.999982  0.999708       1.0
significance

#### 결과 예시 6

In [69]:
pd.DataFrame(t_test_results['filtered_cluster_4']['out_sample'])

                         Sharpe   Sortino      CVaR
Cluster                -0.03701 -0.051173 -0.032039
RandomMean            -0.032018  -0.04126 -0.032631
p-value (one-sided >)  0.915556  0.982709  0.032426
significance                                     **

#### 결과 예시 7

In [70]:
pd.DataFrame(t_test_results['filtered_cluster_6']['in_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.015073  0.018457 -0.039383
RandomMean             0.023203  0.028469 -0.034747
p-value (one-sided >)       1.0       1.0       1.0
significance

#### 결과 예시 8

In [71]:
pd.DataFrame(t_test_results['filtered_cluster_6']['out_sample'])

                         Sharpe   Sortino      CVaR
Cluster               -0.065877 -0.079929 -0.035523
RandomMean            -0.026956 -0.032623 -0.030058
p-value (one-sided >)       1.0       1.0       1.0
significance

#### 결과 예시 9

In [72]:
pd.DataFrame(t_test_results['filtered_cluster_7']['in_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.006479  0.008457 -0.035307
RandomMean             0.020627  0.026186 -0.035556
p-value (one-sided >)       1.0       1.0  0.108748
significance

#### 결과 예시 10

In [73]:
pd.DataFrame(t_test_results['filtered_cluster_7']['out_sample'])

                         Sharpe   Sortino      CVaR
Cluster                0.010778  0.014296 -0.028259
RandomMean            -0.021637 -0.027724 -0.030988
p-value (one-sided >)       0.0       0.0       0.0
significance                ***       ***       ***

### 시각화 결과 저장

In [74]:
import matplotlib.pyplot as plt
import os

# 저장 폴더 생성
os.makedirs('plot', exist_ok=True)

metrics_to_plot = ['Sharpe', 'Sortino', 'CVaR']
periods = ['in_sample', 'out_sample']

for period in periods:
    for metric in metrics_to_plot:
        fig, ax = plt.subplots(figsize=(10, 4))

        cluster_names = []
        random_means = []
        random_stds = []
        cluster_values = []

        for cluster_name in cluster_metrics_summary.keys():
            if cluster_name not in random_metrics_summary:
                continue

            cluster_names.append(cluster_name)
            random_df = random_metrics_summary[cluster_name][period]
            cluster_val = cluster_metrics_summary[cluster_name][period][metric]

            random_means.append(random_df[metric].mean())
            random_stds.append(random_df[metric].std())
            cluster_values.append(cluster_val)

        # 막대 그래프 (랜덤 평균)
        y_pos = range(len(cluster_names))
        ax.barh(y_pos, random_means, xerr=random_stds, color='lightgray', edgecolor='black',
                label='Random (mean ± std)', alpha=0.7)

        # 클러스터 포트폴리오 값 (빨간 점)
        ax.scatter(cluster_values, y_pos, color='red', label='Cluster Portfolio', zorder=3)

        # 레이블 및 제목 설정
        ax.set_yticks(y_pos)
        ax.set_yticklabels(cluster_names)
        ax.set_xlabel(metric)
        ax.set_title(f'{metric} Comparison (Random vs Cluster) - {period}')
        ax.legend()
        ax.grid(True, axis='x', linestyle='--', alpha=0.5)
        plt.tight_layout()

        # 파일명 생성 및 저장
        filename = f'plot/{period}_{metric.lower()}_plot.png'
        plt.savefig(filename)
        print(f"✅ 저장 완료: {filename}")

        plt.close()

✅ 저장 완료: plot/in_sample_sharpe_plot.png
✅ 저장 완료: plot/in_sample_sortino_plot.png
✅ 저장 완료: plot/in_sample_cvar_plot.png
✅ 저장 완료: plot/out_sample_sharpe_plot.png
✅ 저장 완료: plot/out_sample_sortino_plot.png
✅ 저장 완료: plot/out_sample_cvar_plot.png